Repository ArkEcosystem/mobile-wallet, pull requests merged in 2019-07, with the labels that each got.

#356 fix: handle transaction amount as a string
  package-lock.json
  package.json
  src/components/amount/amount.html
  src/components/amount/amount.ts
  src/models/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#357 fix typo preminned to premined
  src/app/app.constants.ts
  src/pages/delegates/delegates.ts
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved

#359 chore: bump to 1.5.0
  config.xml
  package.json
Labels: Complexity: Low, Type: Task

#363 chore: merge develop into master
  config.xml
  package-lock.json
  package.json
  src/app/app.constants.ts
  src/components/amount/amount.html
  src/components/amount/amount.ts
  src/models/transaction.ts
  src/pages/delegates/delegates.html
  src/pages/delegates/delegates.ts
  src/pages/network-status/network-status.html
  src/pages/network-status/network-status.ts
  src/pages/transaction/transaction-send/transaction-send.ts
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/pages/wallet/wallet-import-manual/wallet-import-manual.html
  src/pages/wallet/wallet-import-manual/wallet-import-manual.ts
  src/pages/wallet/wallet-import/wallet-import.base.ts
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.ts
  src/providers/address-checker/address-checker.ts
  src/providers/ark-api/ark-api.ts
  src/utils/ark-client.ts
  tsconfig.json
Labels: Complexity: Undetermined, Type: Task

#365 fix: update network when peer list is empty
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Bugfix

#367 fix: set address value after rendering in the transfer page
  src/pages/transaction/transaction-send/transaction-send.ts
Labels: Complexity: Low, Type: Bugfix

#369 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task
