Repository ArkEcosystem/mobile-wallet, pull requests merged in 2019-06, with the labels that each got.

#339 fix: update the wallet in the correct profile
  src/models/profile.ts
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/pages/wallet/wallet-list/wallet-list.ts
  src/providers/local-notifications/local-notifications.ts
  src/providers/user-data/user-data.ts
Labels: Complexity: Low, Type: Bugfix

#340 Typo: Fix some punctuation mistakes
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved

#342 chore: bump to 1.4.3
  config.xml
  package.json
Labels: Complexity: Low, Type: Task

#343 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#344 chore: update ark-ts to change the peer config endpoint
  package-lock.json
  package.json
Labels: Complexity: Medium, Type: Task

#346 fix: get fees for 7 days instead of 30
  package.json
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Bugfix

#350 refactor: migrate to v2 api
  package-lock.json
  package.json
  src/app/app.constants.ts
  src/pages/delegates/delegates.html
  src/pages/delegates/delegates.ts
  src/pages/network-status/network-status.html
  src/pages/network-status/network-status.ts
  src/pages/transaction/transaction-send/transaction-send.ts
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/pages/wallet/wallet-import/wallet-import.base.ts
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.ts
  src/providers/address-checker/address-checker.ts
  src/providers/ark-api/ark-api.ts
  src/utils/ark-client.ts
  tsconfig.json
Labels: Complexity: Undetermined, Status: In Progress, Type: Refactor

#354 feat: handle enter key when manually importing wallet
  src/pages/wallet/wallet-import-manual/wallet-import-manual.html
  src/pages/wallet/wallet-import-manual/wallet-import-manual.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Feature

#355 refactor: use activeDelegates provided by network
  src/pages/delegates/delegates.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor
