Repository ArkEcosystem/mobile-wallet, pull requests merged in 2019-09, with the labels that each got.

#360 refactor: dont check if wallet selected for top wallet transactions
  src/pages/transaction/transaction-show/transaction-show.ts
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.ts
Labels: Bounty: Tier 3, Status: Member Approved

#384 updated Czech translation (#383)
  src/assets/i18n/cs.json
Labels: Complexity: Medium, Status: Member Approved

#386 chore: bump version to 1.5.2
  config.xml
  package.json
Labels: Complexity: Low, Type: Task

#388 chore: merge develop into master
  config.xml
  package.json
  src/assets/i18n/cs.json
  src/assets/i18n/it.json
  src/pages/transaction/transaction-show/transaction-show.ts
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.ts
  src/providers/ark-api/ark-api.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#390 ci: setup github action workflow for testing
  .circleci/config.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Complexity: Medium

#392 refactor: implement peer discovery
  package.json
  src/models/stored-network.ts
  src/pages/network-status/network-status.html
  src/pages/network-status/network-status.ts
  src/providers/ark-api/ark-api.ts
  src/utils/ark-client.ts
  src/utils/ark-peer-discovery.ts
  tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Refactor

#393 refactor: find wallet-api-port to create custom network
  src/modals/custom-network-create/custom-network-create.html
  src/modals/custom-network-create/custom-network-create.ts
  src/pages/profiles/profile-create/profile-create.html
  src/utils/ark-client.ts
Labels: Complexity: Medium, Type: Refactor

#415 chore: bump version to 1.5.3
  config.xml
  package.json
Labels: Complexity: Low, Type: Task

#416 chore: merge develop into master
  .circleci/config.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  config.xml
  package.json
  renovate.json
  src/modals/custom-network-create/custom-network-create.html
  src/modals/custom-network-create/custom-network-create.ts
  src/models/stored-network.ts
  src/pages/network-status/network-status.html
  src/pages/network-status/network-status.ts
  src/pages/profiles/profile-create/profile-create.html
  src/providers/ark-api/ark-api.ts
  src/utils/ark-client.ts
  src/utils/ark-peer-discovery.ts
  tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Task
