Repository ArkEcosystem/mobile-wallet, pull requests merged in 2019-05, with the labels that each got.

#316 fix: change node version to run the tests on CircleCI
  .circleci/config.yml
Labels: Complexity: Low, Type: Bugfix

#315 bugfix: remove productivity
  src/pages/delegates/delegate-detail/delegate-detail.html
  src/pages/delegates/delegates.html
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#292 fix: trim passphrase or address on the importing page
  src/pages/wallet/wallet-import/wallet-import.base.ts
  src/validators/passphrase/passphrase.ts
Labels: Complexity: Low, Type: Bugfix

#318 refactor: use the vendorField length provided by the network
  config.xml
  package-lock.json
  package.json
  src/models/stored-network.ts
  src/pages/transaction/transaction-send/transaction-send.html
  src/pages/transaction/transaction-send/transaction-send.ts
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Medium, Type: Refactor

#319 chore: bump to 1.4.2
  config.xml
  package.json
Labels: Complexity: Low, Type: Task

#291 refactor: set static fee when avg dynamic is greater than max
  src/assets/i18n/en.json
  src/components/input-fee/input-fee.html
  src/components/input-fee/input-fee.scss
  src/components/input-fee/input-fee.ts
  src/pages/transaction/transaction-send/transaction-send.html
  src/pages/transaction/transaction-send/transaction-send.ts
Labels: Complexity: Medium, Type: Refactor

#321 fix: vendor field max length
  src/pages/transaction/transaction-send/transaction-send.ts
Labels: Complexity: Low, Type: Bugfix

#322 fix: set the api port to the active peer
  src/modals/custom-network-create/custom-network-create.ts
  src/pages/transaction/transaction-send/transaction-send.ts
Labels: Complexity: Low, Type: Bugfix

#323 fix: reset the delegates property when switching networks
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Bugfix

#324 fix: fetch dynamic fees from the new endpoint
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Status: Needs Changes, Type: Bugfix

#325 fix: remove peer filtering by status
  package-lock.json
  package.json
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Bugfix

#327 feat: peer force reset to seed
  src/assets/i18n/en.json
  src/pages/network-status/network-status.html
  src/pages/network-status/network-status.ts
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Feature

#326 fix: detect successful transactions correctly
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Bugfix

#328 fix: version on reset peer to seed node
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Type: Bugfix

#298 refactor: qr-code regex
  src/components/qr-scanner/qr-scanner.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#312 feat: add top wallets list
  src/app/app.constants.ts
  src/app/app.html
  src/assets/i18n/en.json
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.html
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.module.ts
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.scss
  src/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.ts
  src/pages/wallet/wallet-top-list/wallet-top-list.html
  src/pages/wallet/wallet-top-list/wallet-top-list.module.ts
  src/pages/wallet/wallet-top-list/wallet-top-list.scss
  src/pages/wallet/wallet-top-list/wallet-top-list.ts
  src/providers/ark-api/ark-api.ts
  src/utils/http-utils.ts
Labels: Bounty: Tier 1, Complexity: High, Status: Member Approved, Type: Feature

#297 fix: show keyboard on ios
  config.xml
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Bugfix

#336 refactor: use the activeDelegates number provided by the network
  src/models/stored-network.ts
  src/providers/ark-api/ark-api.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Member Approved, Status: Needs Changes, Type: Refactor
