Repository ArkEcosystem/mobile-wallet, pull requests merged in 2019-04, with the labels that each got.

#302 Add Polish translation strings
  src/assets/i18n/pl.json
  src/providers/settings-data/settings-data.ts
Labels: Bounty: Tier 3, Complexity: High, Status: Member Approved

#307 Removed duplicate line 109 in Swedish translation file.
  src/assets/i18n/sv.json
Labels: Bounty: Tier 6, Complexity: Low

#309 added simplified chinese translations (Zhong Wen)
  src/assets/i18n/zh.json
  src/providers/settings-data/settings-data.ts
Labels: Complexity: High, Status: Member Approved

#293 misc: setup code owners
  CODEOWNERS
Labels: Complexity: Low, Type: Maintenance

#304 fix: build fail on xcode 10.2
  package.json
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix
