Repository ArkEcosystem/mobile-wallet, pull requests merged in 2019-02, with the labels that each got.

#265 fix: save label only when dismissed with 'submit' role
  src/pages/wallet/wallet-dashboard/modal/set-label/set-label.ts
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
Labels: Bounty: Tier 4, Status: Member Approved

#237 fix: amounts with higher precision
  src/components/amount/amount.ts
Labels: Status: Member Approved

#271 fix: debrand p2p config
  src/modals/custom-network-create/custom-network-create.ts
  src/providers/ark-api/ark-api.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#272 fix: use epoch time provided by network
  src/components/confirm-transaction/confirm-transaction.ts
  src/models/stored-network.ts
  src/models/transaction.ts
  src/models/wallet.ts
  src/pages/transaction/transaction-response/transaction-response.ts
  src/pages/transaction/transaction-show/transaction-show.ts
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/providers/ark-api/ark-api.ts
  src/providers/local-notifications/local-notifications.ts
  src/providers/user-data/user-data.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#273 fix: save account balance immediately
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#268 feat: implement dynamic fee selection for transfer and voting pages
  package-lock.json
  package.json
  src/app/app.scss
  src/assets/i18n/en.json
  src/components/input-fee/input-fee.html
  src/components/input-fee/input-fee.module.ts
  src/components/input-fee/input-fee.scss
  src/components/input-fee/input-fee.ts
  src/modals/confirm-transaction/confirm-transaction.ts
  src/models/stored-network.ts
  src/models/transaction.ts
  src/pages/delegates/delegate-detail/delegate-detail.html
  src/pages/delegates/delegate-detail/delegate-detail.module.ts
  src/pages/delegates/delegate-detail/delegate-detail.scss
  src/pages/delegates/delegate-detail/delegate-detail.ts
  src/pages/delegates/delegates.ts
  src/pages/transaction/transaction-send/transaction-send.html
  src/pages/transaction/transaction-send/transaction-send.module.ts
  src/pages/transaction/transaction-send/transaction-send.ts
  src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.html
  src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.module.ts
  src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.ts
  src/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/pipes/units-satoshi/units-satoshi.ts
  src/providers/ark-api/ark-api.ts
  src/theme/variables.scss
  src/utils/ark-utility.ts
  test/tsconfig.test.json
Labels: Complexity: High, Status: Needs Changes, Status: Needs Review, Type: Feature

#276 chore: bump version to 1.4.0
  config.xml
  package-lock.json
  package.json
  src/pages/wallet/wallet-import-manual/wallet-import-manual.html
Labels: Complexity: Low, Status: Needs Review, Type: Task

#277 hotfix: readd sqlite as it's used for backend storage
  config.xml
  package-lock.json
  package.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#286 fix: input-fees to input
  src/pages/delegates/delegate-detail/delegate-detail.html
  src/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.html
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Bugfix
