Repository ArkEcosystem/mobile-wallet, pull requests merged in 2020-09, with the labels that each got.

#668 feat: label legacy magistrate and AIP36 transaction types
  .github/workflows/test.yml
  src/app/app.constants.ts
  src/app/models/transaction.spec.ts
  src/app/models/transaction.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.html
  src/assets/i18n/en.json
  test/fixture/transactions/business-registration.json
  test/fixture/transactions/legacy-business-registration.json
  test/fixture/transactions/second-signature.json
  test/fixture/transactions/transfer.json
  test/fixture/transactions/unknown-registration.json
  tsconfig.json
Labels: Complexity: High, Status: Needs Review, Type: Feature

#675 refactor: use default peer on known networks
  config.xml
  package.json
  src/app/modals/custom-network-create/custom-network-create.ts
  src/app/modals/custom-network-edit/custom-network-edit.html
  src/app/modals/custom-network-edit/custom-network-edit.ts
  src/app/models/node.ts
  src/app/models/stored-network.ts
  src/app/pages/network/network-status/network-status.html
  src/app/pages/network/network-status/network-status.ts
  src/app/services/ark-api/ark-api.ts
  src/app/utils/ark-client.ts
  src/assets/i18n/en.json
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#681 refactor: update AIP36 transaction labels
  config.xml
  package.json
  src/app/app.constants.ts
  src/app/models/transaction.ts
  src/assets/i18n/en.json
Labels: Complexity: Medium, Type: Refactor

#685 fix: exclude current wallet when updating label
  src/app/services/user-data/user-data.ts
Labels: Complexity: Low, Type: Bugfix

#683 fix: use recipient address to sign transaction
  config.xml
  package.json
  src/app/models/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#686 release: 1.8.6
  config.xml
  package.json
Labels: Complexity: Low, Type: Release
