Repository ArkEcosystem/mobile-wallet, pull requests merged in 2020-04, with the labels that each got.

#556 feat: add bottom drawer component
  package-lock.json
  package.json
  src/app/components/bottom-drawer/bottom-drawer.component.spec.ts
  src/app/components/bottom-drawer/bottom-drawer.component.ts
  src/app/components/bottom-drawer/bottom-drawer.module.ts
  src/app/components/bottom-drawer/bottom-drawer.stories.ts
  src/app/components/input-address/input-address.spec.ts
  src/app/components/wallet-picker/wallet-picker.component.pcss
  src/app/components/wallet-picker/wallet-picker.modal.html
  src/app/components/wallet-picker/wallet-picker.modal.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.module.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/assets/styles/app.pcss
Labels: Complexity: High, Type: Feature

#560 test: add ark api test cases
  .github/workflows/test.yml
  src/app/services/ark-api/ark-api.spec.ts
  src/app/services/ark-api/ark-api.ts
  test/fixture/delegates.fixture.ts
  test/fixture/transactions-fees.fixture.ts
Labels: Complexity: High, Environment: Test, Test: Unit

#564 feat: add status component
  src/app/components/alert/alert.component.html
  src/app/components/alert/alert.component.scss
  src/app/components/alert/alert.component.spec.ts
  src/app/components/alert/alert.component.ts
  src/app/components/alert/alert.module.ts
  src/app/components/alert/alert.stories.ts
  src/assets/img/light/alert/alert-error.png
  src/assets/img/light/alert/alert-success.png
  src/assets/svg/alert.svg
  src/assets/svg/checkmark.svg
  src/assets/svg/close.svg
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#562 feat: preserve whitespace in passphrase and truncate long profile names
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/modals/wallet-backup/wallet-backup.html
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved

#566 feat: add wallet identicon component
  package-lock.json
  package.json
  src/app/components/identicon/identicon.component.html
  src/app/components/identicon/identicon.component.pcss
  src/app/components/identicon/identicon.component.spec.ts
  src/app/components/identicon/identicon.component.ts
  src/app/components/identicon/identicon.config.ts
  src/app/components/identicon/identicon.module.ts
  src/app/components/identicon/identicon.stories.ts
Labels: Complexity: Medium, Type: Feature

#567 refactor: redesign intro page
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/intro/intro-pagination/intro-pagination.component.html
  src/app/intro/intro-pagination/intro-pagination.component.pcss
  src/app/intro/intro-pagination/intro-pagination.component.spec.ts
  src/app/intro/intro-pagination/intro-pagination.component.ts
  src/app/intro/intro-routing.module.ts
  src/app/intro/intro.component.html
  src/app/intro/intro.component.pcss
  src/app/intro/intro.component.spec.ts
  src/app/intro/intro.component.ts
  src/app/intro/intro.module.ts
  src/app/intro/shared/intro.actions.ts
  src/app/intro/shared/intro.config.ts
  src/app/intro/shared/intro.service.spec.ts
  src/app/intro/shared/intro.service.ts
  src/app/intro/shared/intro.state.spec.ts
  src/app/intro/shared/intro.state.ts
  src/app/intro/shared/intro.type.ts
  src/app/pages/intro/intro.html
  src/app/pages/intro/intro.module.ts
  src/app/pages/intro/intro.pcss
  src/app/pages/intro/intro.spec.ts
  src/app/shared/shared.module.ts
  src/assets/img/light/intro/anytime.png
  src/assets/img/light/intro/fast-easy.png
  src/assets/img/light/intro/pincode.png
  src/assets/img/light/intro/security.png
  src/assets/img/light/intro/welcome-aboard.png
  src/assets/img/logo.png
Labels: Complexity: High, Type: Feature

#568 refactor: initial delegates redesign
  .storybook/preview.ts
  karma.conf.js
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/auth.component.html
  src/app/components/identicon/identicon.component.pcss
  src/app/components/identicon/identicon.config.ts
  src/app/components/identicon/identicon.module.ts
  src/app/delegates/delegate-list/delegate-list.component.html
  src/app/delegates/delegate-list/delegate-list.component.pcss
  src/app/delegates/delegate-list/delegate-list.component.spec.ts
  src/app/delegates/delegate-list/delegate-list.component.ts
  src/app/delegates/delegate-list/delegate-list.module.ts
  src/app/delegates/delegate-list/delegate-list.stories.ts
  src/app/delegates/delegate-search/delegate-search.component.html
  src/app/delegates/delegate-search/delegate-search.component.pcss
  src/app/delegates/delegate-search/delegate-search.component.ts
  src/app/delegates/delegate-search/delegate-search.controller.ts
  src/app/delegates/delegate-search/delegate-search.module.ts
  src/app/delegates/delegate-search/delegate-search.stories.ts
  src/app/delegates/delegate-unvote-banner/delegate-unvote-banner.component.html
  src/app/delegates/delegate-unvote-banner/delegate-unvote-banner.component.pcss
  src/app/delegates/delegate-unvote-banner/delegate-unvote-banner.component.spec.ts
  src/app/delegates/delegate-unvote-banner/delegate-unvote-banner.component.ts
  src/app/delegates/delegate-unvote-banner/delegate-unvote-banner.stories.ts
  src/app/delegates/delegates-routing.module.ts
  src/app/delegates/delegates.component.html
  src/app/delegates/delegates.component.ts
  src/app/delegates/delegates.module.ts
  src/app/delegates/shared/delegate.actions.ts
  src/app/delegates/shared/delegate.config.ts
  src/app/delegates/shared/delegate.service.mock.ts
  src/app/delegates/shared/delegate.service.ts
  src/app/delegates/shared/delegate.state.spec.ts
  src/app/delegates/shared/delegate.state.ts
  src/app/delegates/shared/delegate.types.ts
  src/assets/styles/app.pcss
  src/assets/svg/menu.svg
  src/assets/svg/search.svg
  src/global.scss
  src/theme/variables.scss
Labels: Complexity: High, Type: Refactor

#569 fix: authorization confirmation and tweaks
  src/app/app.module.ts
  src/app/auth/auth-pin/auth-pin.component.spec.ts
  src/app/auth/auth-pin/auth-pin.component.ts
  src/app/auth/auth.component.spec.ts
  src/app/auth/auth.component.ts
  src/app/auth/auth.module.ts
  src/app/auth/auth.stories.ts
  src/app/auth/shared/auth.actions.ts
  src/app/auth/shared/auth.config.ts
  src/app/auth/shared/auth.controller.spec.ts
  src/app/auth/shared/auth.controller.ts
  src/app/auth/shared/auth.service.spec.ts
  src/app/auth/shared/auth.service.ts
  src/app/auth/shared/auth.state.spec.ts
  src/app/auth/shared/auth.state.ts
  src/app/auth/shared/auth.types.ts
  src/app/components/alert/alert.module.ts
  src/app/components/bottom-drawer/bottom-drawer.stories.ts
  src/app/components/input-address/input-address.module.ts
  src/app/components/input-address/input-address.stories.ts
  src/app/components/input-currency/input-currency.module.ts
  src/app/components/input-currency/input-currency.stories.ts
  src/app/components/input-fee/input-fee.module.ts
  src/app/components/viewer-log/viewer-log.component.module.ts
  src/app/components/viewer-log/viewer-log.modal.module.ts
  src/app/components/viewer-log/viewer-log.stories.ts
  src/app/components/wallet-picker/wallet-picker.component.module.ts
  src/app/components/wallet-picker/wallet-picker.modal.module.ts
  src/app/components/wallet-picker/wallet-picker.stories.ts
  src/app/delegates/delegate-search/delegate-search.module.ts
  src/app/delegates/delegates.module.ts
  src/app/pages/contacts/contact-create/contact-create.module.ts
  src/app/pages/delegates/delegate-detail/delegate-detail.module.ts
  src/app/pages/delegates/delegates.ts
  src/app/pages/login/login.module.ts
  src/app/pages/login/login.ts
  src/app/pages/network/network-overview/network-overview.module.ts
  src/app/pages/profiles/profile-signin/profile-signin.ts
  src/app/pages/settings/settings.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/pages/wallet/wallet-import-manual/wallet-import-manual.ts
  src/app/pages/wallet/wallet-import/wallet-import.base.ts
  src/app/pages/wallet/wallet-import/wallet-import.ts
  src/app/pages/wallet/wallet-list/wallet-list.ts
  src/app/shared.module.ts
Labels: Complexity: Medium, Type: Bugfix

#573 feat: allow removal of wallet label
  src/app/pages/wallet/wallet-dashboard/modal/set-label/set-label.html
  src/app/pages/wallet/wallet-dashboard/modal/set-label/set-label.ts
  src/app/services/user-data/user-data.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#574 refactor: empty wallets list redesign
  .storybook/addons.js
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/wallets/wallets-empty-list/wallets-empty-list.component.html
  src/app/wallets/wallets-empty-list/wallets-empty-list.component.spec.ts
  src/app/wallets/wallets-empty-list/wallets-empty-list.component.ts
  src/app/wallets/wallets-empty-list/wallets-empty-list.module.ts
  src/app/wallets/wallets-empty-list/wallets-empty-list.stories.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#575 refactor: initial transactions module
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/input-amount/input-amount.component.ts
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-fee/input-fee.component.ts
  src/app/delegates/delegate-search/delegate-search.controller.ts
  src/app/delegates/delegate-search/delegate-search.stories.ts
  src/app/delegates/delegate-unvote-banner/delegate-unvote-banner.component.html
  src/app/delegates/delegates.component.html
  src/app/delegates/delegates.component.ts
  src/app/delegates/shared/delegate.service.mock.ts
  src/app/delegates/shared/delegate.types.ts
  src/app/models/transaction.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pipes/market-number/market-number.ts
  src/app/services/ark-api/ark-api.ts
  src/app/shared/shared.types.ts
  src/app/transactions/shared/transaction-form-state/transaction-form.actions.ts
  src/app/transactions/shared/transaction-form-state/transaction-form.state.ts
  src/app/transactions/shared/transaction.pipe.ts
  src/app/transactions/shared/transaction.state.spec.ts
  src/app/transactions/shared/transaction.state.ts
  src/app/transactions/shared/transaction.types.ts
  src/app/transactions/shared/transaction.utils.spec.ts
  src/app/transactions/shared/transaction.utils.ts
  src/app/transactions/transaction-detail/transaction-detail.component.html
  src/app/transactions/transaction-detail/transaction-detail.component.pcss
  src/app/transactions/transaction-detail/transaction-detail.component.spec.ts
  src/app/transactions/transaction-detail/transaction-detail.component.ts
  src/app/transactions/transaction-detail/transaction-detail.module.ts
  src/app/transactions/transaction-detail/transaction-detail.stories.ts
  src/app/transactions/transaction-vote/shared/transaction-vote.controller.spec.ts
  src/app/transactions/transaction-vote/shared/transaction-vote.controller.ts
  src/app/transactions/transaction-vote/shared/transaction-vote.types.ts
  src/app/transactions/transaction-vote/transaction-vote.component.html
  src/app/transactions/transaction-vote/transaction-vote.component.spec.ts
  src/app/transactions/transaction-vote/transaction-vote.component.ts
  src/app/transactions/transaction-vote/transaction-vote.module.ts
  src/app/transactions/transaction-vote/transaction-vote.stories.ts
  src/app/transactions/transactions.module.ts
  src/app/utils/ark-utility.ts
  src/app/utils/bignumber.ts
  src/assets/i18n/en.json
  src/assets/styles/app.pcss
Labels: Complexity: Undetermined, Type: Refactor

#576 refactor: initial network list redesign
  src/app/networks/network-card/network-card.component.html
  src/app/networks/network-card/network-card.component.module.ts
  src/app/networks/network-card/network-card.component.spec.ts
  src/app/networks/network-card/network-card.component.stories.ts
  src/app/networks/network-card/network-card.component.ts
  src/app/networks/network-card/network-card.pcss
  src/app/networks/network-list/network-list.component.html
  src/app/networks/network-list/network-list.component.module.ts
  src/app/networks/network-list/network-list.component.spec.ts
  src/app/networks/network-list/network-list.component.stories.ts
  src/app/networks/network-list/network-list.component.ts
  src/app/networks/networks-routing.module.ts
  src/app/networks/networks.component.html
  src/app/networks/networks.component.module.ts
  src/app/networks/networks.component.ts
  src/app/networks/networks.spec.ts
  src/app/networks/networks.stories.ts
  src/assets/i18n/en.json
  src/assets/img/network/ark-devnet.png
  src/assets/img/network/ark-mainet.png
Labels: Complexity: High, Type: Feature

#578 refactor: add market module
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/market/market.module.ts
  src/app/market/shared/market.actions.ts
  src/app/market/shared/market.config.ts
  src/app/market/shared/market.service.ts
  src/app/market/shared/market.state.spec.ts
  src/app/market/shared/market.state.ts
  src/app/market/shared/market.types.ts
Labels: Complexity: Undetermined, Type: Refactor
