Repository ArkEcosystem/mobile-wallet, pull requests merged in 2020-06, with the labels that each got.

#629 fix(build): add android x support
  config.xml
  package-lock.json
  package.json
Labels: Complexity: Low, Type: Bugfix

#608 feat: redesign wallet passphrase check
  src/app/wallets/wallet-passphrase-check/wallet-passphrase-check.component.html
  src/app/wallets/wallet-passphrase-check/wallet-passphrase-check.component.module.ts
  src/app/wallets/wallet-passphrase-check/wallet-passphrase-check.component.scss
  src/app/wallets/wallet-passphrase-check/wallet-passphrase-check.component.ts
  src/app/wallets/wallet-passphrase-check/wallet-passphrase-check.spec.ts
  src/app/wallets/wallet-passphrase-check/wallet-passphrase-check.stories.ts
  src/assets/i18n/en.json
Labels: Complexity: High, Status: Needs Review, Type: Feature

#630 refactor: replace bignumber with platform SDK
  package.json
  src/app/components/input-amount/input-amount.component.ts
  src/app/components/input-currency/input-currency.component.spec.ts
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-fee/input-fee.component.ts
  src/app/models/transaction.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pipes/market-number/market-number.ts
  src/app/services/ark-api/ark-api.ts
  src/app/transactions/shared/transaction.utils.ts
  src/app/utils/ark-utility.ts
  src/app/utils/bignumber.ts
Labels: Complexity: Medium

#604 feat: wallet details redesign
  .storybook/preview.ts
  src/app/app.module.ts
  src/app/transactions/transaction-list/transaction-list.component.html
  src/app/transactions/transaction-list/transaction-list.component.module.ts
  src/app/transactions/transaction-list/transaction-list.component.scss
  src/app/transactions/transaction-list/transaction-list.component.ts
  src/app/transactions/transaction-list/transaction-list.spec.ts
  src/app/transactions/transaction-list/transaction-list.stories.ts
  src/app/transactions/transaction-row/transaction-row.component.html
  src/app/transactions/transaction-row/transaction-row.component.module.ts
  src/app/transactions/transaction-row/transaction-row.component.scss
  src/app/transactions/transaction-row/transaction-row.component.ts
  src/app/transactions/transaction-row/transaction-row.spec.ts
  src/app/transactions/transaction-row/transaction-row.stories.ts
  src/app/wallets/wallet-card/wallet-card.component.html
  src/app/wallets/wallet-details/wallet-details-routing.module.ts
  src/app/wallets/wallet-details/wallet-details.component.html
  src/app/wallets/wallet-details/wallet-details.component.module.ts
  src/app/wallets/wallet-details/wallet-details.component.scss
  src/app/wallets/wallet-details/wallet-details.component.ts
  src/app/wallets/wallet-details/wallet-details.spec.ts
  src/app/wallets/wallet-details/wallet-details.stories.ts
  src/assets/img/transactions/received-icon.png
  src/assets/img/transactions/sent-icon.png
  src/coins/shared/coin.config.ts
  src/theme/variables.scss
  test/fixture/transactions.fixture.ts
Labels: Complexity: High, Type: Feature

#626 feat: send coin screen
  .storybook/addons.js
  package-lock.json
  package.json
  src/app/components/input-address/input-address.component.html
  src/app/components/input-address/input-address.component.scss
  src/app/components/input-address/input-address.component.ts
  src/app/components/input-address/input-address.spec.ts
  src/app/components/input-currency/input-currency.component.html
  src/app/components/input-currency/input-currency.component.scss
  src/app/components/input-currency/input-currency.component.spec.ts
  src/app/components/recipient-list/recipient-list.component.ts
  src/app/transactions/transaction-send/recipient-list-resume/recipient-list-resume.component.html
  src/app/transactions/transaction-send/recipient-list-resume/recipient-list-resume.component.module.ts
  src/app/transactions/transaction-send/recipient-list-resume/recipient-list-resume.component.scss
  src/app/transactions/transaction-send/recipient-list-resume/recipient-list-resume.component.ts
  src/app/transactions/transaction-send/recipient-list-resume/recipient-list-resume.spec.ts
  src/app/transactions/transaction-send/recipient-list-resume/recipient-list-resume.stories.ts
  src/app/transactions/transaction-send/recipient-list/recipient-list.component.html
  src/app/transactions/transaction-send/recipient-list/recipient-list.component.module.ts
  src/app/transactions/transaction-send/recipient-list/recipient-list.component.scss
  src/app/transactions/transaction-send/recipient-list/recipient-list.component.spec.ts
  src/app/transactions/transaction-send/recipient-list/recipient-list.component.ts
  src/app/transactions/transaction-send/recipient-list/recipient-list.stories.ts
  src/app/transactions/transaction-send/transaction-send.component.html
  src/app/transactions/transaction-send/transaction-send.component.scss
  src/app/transactions/transaction-send/transaction-send.component.ts
  src/app/transactions/transaction-send/transaction-send.module.ts
  src/app/transactions/transaction-send/transaction-send.spec.ts
  src/app/transactions/transaction-send/transaction-send.stories.ts
  src/assets/i18n/en.json
  src/assets/svg/person.svg
  src/assets/svg/qr-code-border.svg
  src/assets/svg/qrcode.svg
  src/assets/svg/swipe_to_delete_instructions.svg
Labels: Complexity: High, Status: Needs Review, Type: Feature

#644 fix: chromedriver version to run e2e job
  .github/workflows/test.yml
  src/app/wallets/wallets.component.scss
Labels: Complexity: Low, Type: Bugfix
