Repository ArkEcosystem/mobile-wallet, pull requests merged in 2020-03, with the labels that each got.

#508 fix: search bar and segment on the delegates screen
  src/app/pages/delegates/delegates.html
  src/app/pages/delegates/delegates.pcss
Labels: Complexity: Low, Type: Bugfix

#509 fix: delegate vote form
  src/app/pages/delegates/delegate-detail/delegate-detail.html
  src/app/pages/delegates/delegate-detail/delegate-detail.module.ts
  src/app/pages/delegates/delegate-detail/delegate-detail.ts
Labels: Complexity: Low, Type: Bugfix

#507 refactor: wallet selection on the transfer screen
  package-lock.json
  package.json
  src/app/components/address-list/address-list.html
  src/app/components/address-list/address-list.pcss
  src/app/components/close-popup/close-popup.html
  src/app/components/input-address/input-address.component.html
  src/app/components/input-address/input-address.component.scss
  src/app/components/input-address/input-address.component.ts
  src/app/components/input-address/input-address.module.ts
  src/app/components/wallet-picker/wallet-picker.component.html
  src/app/components/wallet-picker/wallet-picker.component.module.ts
  src/app/components/wallet-picker/wallet-picker.component.pcss
  src/app/components/wallet-picker/wallet-picker.component.ts
  src/app/components/wallet-picker/wallet-picker.modal.html
  src/app/components/wallet-picker/wallet-picker.modal.module.ts
  src/app/components/wallet-picker/wallet-picker.modal.ts
  src/app/directives/directives.module.ts
  src/app/directives/value-mask-on-blur/value-mask-on-blur.ts
  src/app/models/contact.ts
  src/app/pages/login/login.module.ts
  src/app/pages/login/login.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.module.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pages/wallet/wallet-list/wallet-list.ts
  src/app/services/account-auto-complete/account-auto-complete.ts
  src/app/services/user-data/user-data.ts
  src/assets/styles/app.pcss
  src/assets/styles/auto-complete.pcss
  src/global.scss
Labels: Complexity: High, Type: Refactor

#506 test: add storage service unitary tests
  angular.json
  karma.conf.js
  src/app/services/storage/storage.spec.ts
Labels: Complexity: Low, Environment: Test, Status: Needs Review, Test: Unit

#510 test: fix coverage statistic
  .github/workflows/test.yml
  karma.conf.js
  package-lock.json
  package.json
  test/mocks.ts
  tsconfig.app.json
Labels: Complexity: Medium, Test: Unit

#513 chore: setup ionic appflow
  ionic.config.json
Labels: Complexity: Low, Type: Task

#511 build: enable aot compilation by default
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  angular.json
  package-lock.json
  package.json
Labels: Complexity: Low

#514 chore: setup ionic appflow sdk
  ionic.config.json
  package-lock.json
  package.json
Labels: Complexity: Low, Type: Task

#515 build: change target to es5
  package.json
  tsconfig.app.json
Labels: Complexity: Low

#518 test: add network service test cases
  .lintstagedrc.json
  angular.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/custom-network/custom-network.ts
  src/app/components/input-amount/input-amount.component.ts
  src/app/components/pin-code/pin-code.ts
  src/app/components/wallet-picker/wallet-picker.modal.ts
  src/app/directives/marketnet-only/marketnet-only.ts
  src/app/modals/custom-network-edit/custom-network-edit.ts
  src/app/modals/passphrase-word-tester/passphrase-word-tester.ts
  src/app/modals/wallet-backup/wallet-backup.ts
  src/app/pages/contacts/contact-create/contact-create.ts
  src/app/pages/contacts/contact-list/contact-list.ts
  src/app/pages/delegates/delegate-detail/delegate-detail.ts
  src/app/pages/delegates/delegates.ts
  src/app/pages/login/login.ts
  src/app/pages/network/network-overview/network-overview.page.ts
  src/app/pages/profiles/profile-create/profile-create.ts
  src/app/pages/profiles/profile-signin/profile-signin.ts
  src/app/pages/settings/settings.ts
  src/app/pages/transaction/transaction-response/transaction-response.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pages/transaction/transaction-show/transaction-show.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/pages/wallet/wallet-import-manual/wallet-import-manual.ts
  src/app/pages/wallet/wallet-import/wallet-import.base.ts
  src/app/pages/wallet/wallet-import/wallet-import.ts
  src/app/pages/wallet/wallet-list/wallet-list.ts
  src/app/pipes/account-label/account-label.ts
  src/app/pipes/has-account-label/has-account-label.ts
  src/app/services/address-checker/address-checker.ts
  src/app/services/ark-api/ark-api.ts
  src/app/services/contacts/contacts.ts
  src/app/services/market-data/market-data.ts
  src/app/services/network/network.spec.ts
  src/app/services/network/network.ts
  src/app/services/user-data/user-data.interface.ts
  src/app/services/user-data/user-data.ts
  test/helpers.ts
  test/mocks.ts
  tsconfig.eslint.json
Labels: Complexity: High, Test: Unit

#519 fix: hammerjs with Angular 9
  src/app/app.module.ts
Labels: Complexity: Low, Type: Bugfix

#520 feat: add settings-data unit tests
  karma.conf.js
  src/app/pages/settings/settings.ts
  src/app/services/settings-data/settings-data.spec.ts
  src/app/services/settings-data/settings-data.ts
  src/app/services/storage/storage.spec.ts
  src/app/services/storage/storage.ts
Labels: Complexity: Medium, Environment: Test, Status: Needs Review, Test: Unit, Type: Feature

#521 refactor: input-fee component
  .eslintrc.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/input-currency/input-currency.component.html
  src/app/components/input-currency/input-currency.component.scss
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-currency/input-currency.module.ts
  src/app/components/input-fee/input-fee.component.html
  src/app/components/input-fee/input-fee.component.pcss
  src/app/components/input-fee/input-fee.component.scss
  src/app/components/input-fee/input-fee.component.spec.ts
  src/app/components/input-fee/input-fee.component.ts
  src/app/components/input-fee/input-fee.module.ts
  src/app/directives/directives.module.ts
  src/app/directives/paste-clipboard-value/paste-clipboard-value.ts
  src/app/pages/delegates/delegate-detail/delegate-detail.html
  src/app/pages/delegates/delegate-detail/delegate-detail.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/services/ark-api/ark-api.ts
  src/app/utils/http-utils.ts
  src/assets/i18n/en.json
  src/theme/variables.scss
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#522 test: add auth service unit tests
  src/app/components/pin-code/pin-code.ts
  src/app/modals/pin-code/pin-code.ts
  src/app/pages/intro/intro.ts
  src/app/services/auth/auth.spec.ts
  src/app/services/auth/auth.ts
Labels: Complexity: Medium, Environment: Test, Status: Needs Review, Test: Unit

#524 test: refactor intro page
  karma.conf.js
  src/app/pages/intro/intro.html
  src/app/pages/intro/intro.spec.ts
  src/app/pages/intro/intro.ts
Labels: Complexity: Medium, Test: Unit

#526 fix: input-fee component tweaks
  src/app/components/input-fee/input-fee.component.pcss
  src/global.scss
Labels: Complexity: Low, Type: Bugfix

#527 ci: fix connectivity for building in appflow
  config.xml
  resources/android/xml/network_security_config.xml
Labels: Complexity: Low

#529 chore: update deps and speed up the workflow
  .github/workflows/lint.yml
  .github/workflows/test.yml
  e2e/protractor.conf.js
  karma.conf.js
  package-lock.json
  package.json
  src/app/app.component.spec.ts
Labels: Complexity: Undetermined, Type: Task

#530 test: add contacts unit tests
  src/app/services/contacts/contacts.spec.ts
  src/app/services/contacts/contacts.ts
  src/assets/i18n/en.json
  test/mocks.ts
Labels: Complexity: High, Environment: Test, Status: Needs Review, Test: Unit

#532 test: add user data service specs
  .eslintrc.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/components/input-currency/input-currency.module.ts
  src/app/directives/paste-clipboard-value/paste-clipboard-value.ts
  src/app/pages/intro/intro.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/services/ark-api/ark-api.ts
  src/app/services/contacts/contacts.ts
  src/app/services/user-data/user-data.interface.ts
  src/app/services/user-data/user-data.spec.ts
  src/app/services/user-data/user-data.ts
  test/fixture/networks.fixture.ts
  test/fixture/profiles.fixture.ts
  test/fixture/wallets.fixture.ts
  test/helpers.ts
  test/mocks.ts
Labels: Complexity: Undetermined, Status: Needs Review, Test: Unit

#533 feat: add component stories
  .storybook/main.js
  .storybook/preview.ts
  .storybook/tsconfig.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-currency/input-currency.stories.ts
  src/app/components/input-fee/input-fee.stories.ts
  src/app/components/wallet-picker/wallet-picker.stories.ts
Labels: Complexity: Undetermined, Type: Feature

#534 test: remove testing library
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/components/input-currency/input-currency.component.spec.ts
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-fee/input-fee.component.spec.ts
  src/app/components/input-fee/input-fee.component.ts
  src/app/components/wallet-picker/wallet-picker.component.html
  src/app/components/wallet-picker/wallet-picker.component.spec.ts
  src/app/pages/intro/intro.spec.ts
  src/app/services/event-bus/event-bus.spec.ts
  src/app/services/forge/forge.spec.ts
  src/app/services/forge/forge.ts
  test/fixture/wallets.fixture.ts
  test/helpers.ts
Labels: Complexity: High, Test: Unit

#540 test: add address check unit tests
  package-lock.json
  src/app/services/address-checker/address-checker.spec.ts
  src/app/services/address-checker/address-checker.ts
  test/fixture/transactions.fixture.ts
  test/fixture/wallets.fixture.ts
Labels: Complexity: High, Environment: Test, Test: Unit

#543 refactor: address and fee component tweaks
  config.xml
  src/app/components/input-address/input-address.component.html
  src/app/components/input-address/input-address.component.ts
  src/app/components/input-address/input-address.module.ts
  src/app/components/input-address/input-address.spec.ts
  src/app/components/input-address/input-address.stories.ts
  src/app/components/input-currency/input-currency.component.html
  src/app/components/input-currency/input-currency.component.scss
  src/app/components/input-currency/input-currency.stories.ts
  src/app/components/input-fee/input-fee.component.html
  src/app/components/input-fee/input-fee.component.pcss
  src/app/components/input-fee/input-fee.stories.ts
  src/app/components/passphrase-input/passphrase-input.html
  src/app/components/passphrase-input/passphrase-input.pcss
  src/app/components/passphrase-input/passphrase-input.ts
  src/app/directives/paste-clipboard-value/paste-clipboard-value.ts
  src/app/modals/passphrase-word-tester/passphrase-word-tester.html
  src/app/modals/passphrase-word-tester/passphrase-word-tester.ts
  src/app/pages/contacts/contact-create/contact-create.html
  src/app/pages/contacts/contact-create/contact-create.module.ts
  src/app/pages/contacts/contact-create/contact-create.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pipes/truncate-middle/truncate-middle.ts
  src/assets/styles/app.pcss
  src/global.scss
  src/theme/variables.scss
Labels: Complexity: Undetermined, Type: Refactor

#544 feat: developer mode
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/pin-code/pin-code.ts
  src/app/components/viewer-log/viewer-log.component.html
  src/app/components/viewer-log/viewer-log.component.module.ts
  src/app/components/viewer-log/viewer-log.component.spec.ts
  src/app/components/viewer-log/viewer-log.component.ts
  src/app/components/viewer-log/viewer-log.modal.html
  src/app/components/viewer-log/viewer-log.modal.module.ts
  src/app/components/viewer-log/viewer-log.modal.spec.ts
  src/app/components/viewer-log/viewer-log.modal.ts
  src/app/components/viewer-log/viewer-log.stories.ts
  src/app/models/settings.ts
  src/app/pages/settings/settings.html
  src/app/pages/settings/settings.module.ts
  src/app/pages/settings/settings.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/services/error-handler/error-handler.service.ts
  src/app/services/logger/logger.service.ts
  src/app/services/toast/toast.ts
  src/assets/i18n/en.json
Labels: Complexity: High, Type: Feature

#545 fix: passphrase confirmation style tweaks
  src/app/components/passphrase-input/passphrase-input.html
  src/app/modals/enter-second-passphrase/enter-second-passphrase.html
  src/app/modals/passphrase-word-tester/passphrase-word-tester.html
Labels: Complexity: Low, Type: Bugfix

#547 fix: back button in the wallet dashboard screen
  src/app/app.component.ts
Labels: Complexity: Low, Type: Bugfix

#552 chore: update deps
  package-lock.json
  package.json
Labels: Complexity: Undetermined, Type: Task

#553 chore: resolve UIWebView API deprecation
  config.xml
Labels: Complexity: Low, Type: Task

#554 fix: capitalize translation items
  src/assets/i18n/en.json
Labels: Complexity: Low, Type: Bugfix

#555 feat: add neo-api unit tests
  src/app/services/neo-api/neo-api.spec.ts
Labels: Complexity: Low, Environment: Test, Test: Unit, Type: Feature
