Repository ArkEcosystem/mobile-wallet, pull requests merged in 2020-05, with the labels that each got.

#585 chore: update deps
  config.xml
  package-lock.json
  package.json
  src/app/market/shared/market.service.ts
  src/app/market/shared/market.types.ts
  tsconfig.app.json
  tsconfig.spec.json
Labels: Complexity: Undetermined, Type: Task

#586 feat: add custom font family
  package-lock.json
  package.json
  src/assets/fonts/Inter Bold.eot
  src/assets/fonts/Inter Bold.woff
  src/assets/fonts/Inter Bold.woff2
  src/assets/fonts/Inter Medium.eot
  src/assets/fonts/Inter Medium.woff
  src/assets/fonts/Inter Medium.woff2
  src/assets/fonts/Inter Regular.eot
  src/assets/fonts/Inter Regular.woff
  src/assets/fonts/Inter Regular.woff2
  src/assets/fonts/Inter Semi Bold.eot
  src/assets/fonts/Inter Semi Bold.woff
  src/assets/fonts/Inter Semi Bold.woff2
  src/assets/fonts/Inter.css
  src/global.scss
  src/theme/variables.scss
  webpack.config.js
Labels: Complexity: Medium, Type: Feature

#593 feat: wallets list redesign
  .storybook/addons.js
  .storybook/preview.ts
  .storybook/tsconfig.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/networks/network-card/network-card.component.html
  src/app/pages/delegates/delegates.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/wallet/wallet.module.ts
  src/app/wallets/wallet-card/wallet-card.component.html
  src/app/wallets/wallet-card/wallet-card.component.module.ts
  src/app/wallets/wallet-card/wallet-card.component.spec.ts
  src/app/wallets/wallet-card/wallet-card.component.ts
  src/app/wallets/wallet-card/wallet-card.pcss
  src/app/wallets/wallet-card/wallet-card.stories.ts
  src/app/wallets/wallet-list-actions/wallet-list-actions.component.html
  src/app/wallets/wallet-list-actions/wallet-list-actions.component.module.ts
  src/app/wallets/wallet-list-actions/wallet-list-actions.component.ts
  src/app/wallets/wallet-list-actions/wallet-list-actions.spec.ts
  src/app/wallets/wallet-list-actions/wallet-list-actions.stories.ts
  src/app/wallets/wallet-list-empty/wallet-list-empty.component.html
  src/app/wallets/wallet-list-empty/wallet-list-empty.component.module.ts
  src/app/wallets/wallet-list-empty/wallet-list-empty.component.spec.ts
  src/app/wallets/wallet-list-empty/wallet-list-empty.component.ts
  src/app/wallets/wallet-list-empty/wallet-list-empty.stories.ts
  src/app/wallets/wallet-list-header/wallet-list-header.component.html
  src/app/wallets/wallet-list-header/wallet-list-header.component.module.ts
  src/app/wallets/wallet-list-header/wallet-list-header.component.scss
  src/app/wallets/wallet-list-header/wallet-list-header.component.spec.ts
  src/app/wallets/wallet-list-header/wallet-list-header.component.ts
  src/app/wallets/wallet-list-header/wallet-list-header.stories.ts
  src/app/wallets/wallet-list/wallet-list.component.html
  src/app/wallets/wallet-list/wallet-list.component.module.ts
  src/app/wallets/wallet-list/wallet-list.component.spec.ts
  src/app/wallets/wallet-list/wallet-list.component.ts
  src/app/wallets/wallet-list/wallet-list.stories.ts
  src/app/wallets/wallets-empty-list/wallets-empty-list.component.html
  src/app/wallets/wallets-empty-list/wallets-empty-list.stories.ts
  src/app/wallets/wallets-routing.module.ts
  src/app/wallets/wallets.component.html
  src/app/wallets/wallets.component.module.ts
  src/app/wallets/wallets.component.scss
  src/app/wallets/wallets.component.spec.ts
  src/app/wallets/wallets.component.ts
  src/app/wallets/wallets.controller.ts
  src/assets/img/coins/ark.png
  src/assets/img/coins/btc.png
  src/coins/shared/coin.config.ts
  src/global.scss
  test/mocks.ts
Labels: Complexity: Undetermined, Status: Needs Review

#605 feat: redesign wallet passphrase list
  src/app/wallets/wallet-passphrase-list/wallet-passphrase-list.component.html
  src/app/wallets/wallet-passphrase-list/wallet-passphrase-list.component.module.ts
  src/app/wallets/wallet-passphrase-list/wallet-passphrase-list.component.scss
  src/app/wallets/wallet-passphrase-list/wallet-passphrase-list.component.spec.ts
  src/app/wallets/wallet-passphrase-list/wallet-passphrase-list.component.ts
  src/app/wallets/wallet-passphrase-list/wallet-passphrase-list.stories.ts
  src/assets/i18n/en.json
  tailwind.config.js
Labels: Complexity: High, Type: Feature

#610 fix: profile signin page height
  src/app/components/empty-list/empty-list.html
  src/app/pages/profiles/profile-signin/profile-signin.html
Labels: Complexity: Low, Type: Bugfix

#611 fix: settings page header on android
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/settings/settings.html
  src/app/pages/settings/settings.module.ts
  src/app/pages/settings/settings.scss
  src/app/pages/settings/settings.ts
  src/app/settings/settings.component.html
  src/app/settings/settings.component.pcss
  src/app/settings/settings.component.ts
  src/app/settings/settings.module.ts
  src/assets/styles/app.pcss
Labels: Complexity: High, Type: Bugfix

#619 fix: subscribe auth ctrl methods
  src/app/auth/shared/auth.controller.ts
  src/app/pages/delegates/delegates.ts
  src/app/pages/wallet/wallet-list/wallet-list.ts
  src/app/settings/settings.component.spec.ts
  src/app/settings/settings.component.ts
Labels: Complexity: Medium, Type: Bugfix

#622 fix: onboarding image size on iOS
  src/app/onboarding/onboarding.component.html
  src/app/onboarding/onboarding.component.pcss
  src/assets/svg/onboarding-easy.svg
  src/assets/svg/onboarding-security.svg
  src/assets/svg/onboarding-welcome.svg
  src/global.scss
Labels: Complexity: High, Type: Bugfix

#624 hotfix: release 1.8.1
  .github/workflows/test.yml
  config.xml
  package-lock.json
  package.json
  src/app/pages/profiles/profile-signin/profile-signin.html
Labels: Complexity: Low, Type: Bugfix

#613 feat: add recipient list component
  src/app/components/recipient-list/recipient-list.component.html
  src/app/components/recipient-list/recipient-list.component.module.ts
  src/app/components/recipient-list/recipient-list.component.scss
  src/app/components/recipient-list/recipient-list.component.spec.ts
  src/app/components/recipient-list/recipient-list.component.ts
  src/app/components/recipient-list/recipient-list.stories.ts
  src/assets/svg/edit.svg
Labels: Complexity: High, Status: Needs Review, Type: Feature
