Repository ArkEcosystem/mobile-wallet, pull requests merged in 2020-02, with the labels that each got.

#479 fix: remove cordova-plugin-background-mode
  config.xml
  package-lock.json
  package.json
Labels: Complexity: Low, Type: Bugfix

#482 refactor: update @ionic/angular to v5
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/components/close-popup/close-popup.html
  src/app/modals/confirm-transaction/confirm-transaction.html
  src/app/modals/custom-network-create/custom-network-create.html
  src/app/modals/custom-network-edit/custom-network-edit.html
  src/app/modals/custom-network-edit/custom-network-edit.ts
  src/app/modals/custom-network-manage/custom-network-manage.html
  src/app/modals/enter-second-passphrase/enter-second-passphrase.html
  src/app/modals/generate-entropy/generate-entropy.html
  src/app/modals/passphrase-word-tester/passphrase-word-tester.html
  src/app/modals/wallet-backup/wallet-backup.html
  src/app/pages/contacts/contact-create/contact-create.html
  src/app/pages/contacts/contact-list/contact-list.html
  src/app/pages/contacts/contact-list/contact-list.ts
  src/app/pages/delegates/delegate-detail/delegate-detail.html
  src/app/pages/delegates/delegates.html
  src/app/pages/intro/intro.html
  src/app/pages/network-status/network-status.html
  src/app/pages/profiles/profile-create/profile-create.html
  src/app/pages/profiles/profile-create/profile-create.ts
  src/app/pages/profiles/profile-signin/profile-signin.html
  src/app/pages/profiles/profile-signin/profile-signin.ts
  src/app/pages/settings/settings.html
  src/app/pages/transaction/transaction-receive/transaction-receive.html
  src/app/pages/transaction/transaction-response/transaction-response.html
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-show/transaction-show.html
  src/app/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.html
  src/app/pages/wallet/wallet-dashboard/modal/register-second-passphrase/register-second-passphrase.html
  src/app/pages/wallet/wallet-dashboard/modal/set-label/set-label.html
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.html
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.scss
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/pages/wallet/wallet-import-manual/wallet-import-manual.html
  src/app/pages/wallet/wallet-import/wallet-import.html
  src/app/pages/wallet/wallet-list/wallet-list.html
  src/app/pages/wallet/wallet-list/wallet-list.ts
  src/app/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.html
  src/app/pages/wallet/wallet-top-list/wallet-top-list.html
  src/assets/svg/arrow-down.svg
  src/assets/svg/arrow-up.svg
Labels: Complexity: Medium, Type: Refactor

#487 fix: fiat amount correlation
  src/app/components/amount/amount.html
  src/app/components/amount/amount.model.ts
  src/app/components/amount/amount.ts
  src/app/components/input-amount/input-amount.component.html
  src/app/components/input-amount/input-amount.component.scss
  src/app/components/input-amount/input-amount.component.ts
  src/app/components/input-amount/input-amount.module.ts
  src/app/components/input-currency/input-currency.component.html
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-currency/input-currency.module.ts
  src/app/components/input-fee/input-fee.component.html
  src/app/components/input-fee/input-fee.component.scss
  src/app/components/input-fee/input-fee.component.ts
  src/app/components/input-fee/input-fee.module.ts
  src/app/models/transaction.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.html
  src/app/pages/transaction/transaction-receive/transaction-receive.module.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.module.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pipes/market-number/market-number.ts
  src/app/services/ark-api/ark-api.ts
  src/app/utils/ark-utility.ts
  src/app/utils/bignumber.ts
Labels: Complexity: High, Type: Bugfix

#488 feat: add network-overview page
  src/app/app-routing.module.ts
  src/app/components/address-list/address-list.html
  src/app/modals/custom-network-edit/custom-network-edit.html
  src/app/modals/custom-network-edit/custom-network-edit.ts
  src/app/models/contact.ts
  src/app/pages/contacts/contact-list/contact-list.ts
  src/app/pages/network/network-overview/network-overview.module.ts
  src/app/pages/network/network-overview/network-overview.page.html
  src/app/pages/network/network-overview/network-overview.page.ts
  src/app/pages/network/network-status/network-status.html
  src/app/pages/network/network-status/network-status.module.ts
  src/app/pages/network/network-status/network-status.pcss
  src/app/pages/network/network-status/network-status.ts
  src/app/pages/profiles/profile-signin/profile-signin.ts
  src/app/pages/settings/settings.ts
  src/app/services/user-data/user-data.ts
  src/assets/i18n/en.json
Labels: Complexity: High, Type: Feature

#493 fix: multipayment additional checks
  src/app/components/input-fee/input-fee.component.html
  src/app/models/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#492 fix: ensure numeric type for network version
  src/app/modals/custom-network-edit/custom-network-edit.html
  src/app/pages/transaction/transaction-send/transaction-send.ts
Labels: Complexity: Low, Type: Bugfix

#494 release: hotfix 1.7.1
  config.xml
  package.json
  src/app/app-routing.module.ts
  src/app/components/address-list/address-list.html
  src/app/components/amount/amount.html
  src/app/components/amount/amount.model.ts
  src/app/components/amount/amount.ts
  src/app/components/input-amount/input-amount.component.html
  src/app/components/input-amount/input-amount.component.scss
  src/app/components/input-amount/input-amount.component.ts
  src/app/components/input-amount/input-amount.module.ts
  src/app/components/input-currency/input-currency.component.html
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-currency/input-currency.module.ts
  src/app/components/input-fee/input-fee.component.html
  src/app/components/input-fee/input-fee.component.scss
  src/app/components/input-fee/input-fee.component.ts
  src/app/components/input-fee/input-fee.module.ts
  src/app/modals/custom-network-edit/custom-network-edit.html
  src/app/modals/custom-network-edit/custom-network-edit.ts
  src/app/models/contact.ts
  src/app/models/transaction.ts
  src/app/pages/contacts/contact-list/contact-list.ts
  src/app/pages/delegates/delegates.html
  src/app/pages/network/network-overview/network-overview.module.ts
  src/app/pages/network/network-overview/network-overview.page.html
  src/app/pages/network/network-overview/network-overview.page.ts
  src/app/pages/network/network-status/network-status.html
  src/app/pages/network/network-status/network-status.module.ts
  src/app/pages/network/network-status/network-status.pcss
  src/app/pages/network/network-status/network-status.ts
  src/app/pages/profiles/profile-signin/profile-signin.ts
  src/app/pages/settings/settings.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.html
  src/app/pages/transaction/transaction-receive/transaction-receive.module.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.module.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pages/transaction/transaction-show/transaction-show.html
  src/app/pages/transaction/transaction-show/transaction-show.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/pages/wallet/wallet-list/wallet-list.html
  src/app/pipes/market-number/market-number.ts
  src/app/services/ark-api/ark-api.ts
  src/app/services/user-data/user-data.ts
  src/app/utils/ark-utility.ts
  src/app/utils/bignumber.ts
  src/assets/i18n/en.json
  src/assets/styles/auto-complete.pcss
Labels: Complexity: Undetermined, Type: Release

#498 chore: update codeowners
  CODEOWNERS
Labels: Complexity: Low, Type: Task

#501 chore: merge master into develop
  config.xml
  package.json
  src/app/app-routing.module.ts
  src/app/components/address-list/address-list.html
  src/app/components/amount/amount.html
  src/app/components/amount/amount.model.ts
  src/app/components/amount/amount.ts
  src/app/components/input-amount/input-amount.component.html
  src/app/components/input-amount/input-amount.component.scss
  src/app/components/input-amount/input-amount.component.ts
  src/app/components/input-amount/input-amount.module.ts
  src/app/components/input-currency/input-currency.component.html
  src/app/components/input-currency/input-currency.component.ts
  src/app/components/input-currency/input-currency.module.ts
  src/app/components/input-fee/input-fee.component.html
  src/app/components/input-fee/input-fee.component.scss
  src/app/components/input-fee/input-fee.component.ts
  src/app/components/input-fee/input-fee.module.ts
  src/app/modals/custom-network-edit/custom-network-edit.html
  src/app/modals/custom-network-edit/custom-network-edit.ts
  src/app/models/contact.ts
  src/app/models/transaction.ts
  src/app/pages/contacts/contact-list/contact-list.ts
  src/app/pages/delegates/delegates.html
  src/app/pages/network/network-overview/network-overview.module.ts
  src/app/pages/network/network-overview/network-overview.page.html
  src/app/pages/network/network-overview/network-overview.page.ts
  src/app/pages/network/network-status/network-status.html
  src/app/pages/network/network-status/network-status.module.ts
  src/app/pages/network/network-status/network-status.pcss
  src/app/pages/network/network-status/network-status.ts
  src/app/pages/profiles/profile-signin/profile-signin.ts
  src/app/pages/settings/settings.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.html
  src/app/pages/transaction/transaction-receive/transaction-receive.module.ts
  src/app/pages/transaction/transaction-receive/transaction-receive.ts
  src/app/pages/transaction/transaction-send/transaction-send.html
  src/app/pages/transaction/transaction-send/transaction-send.module.ts
  src/app/pages/transaction/transaction-send/transaction-send.ts
  src/app/pages/transaction/transaction-show/transaction-show.html
  src/app/pages/transaction/transaction-show/transaction-show.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/pages/wallet/wallet-list/wallet-list.html
  src/app/pipes/market-number/market-number.ts
  src/app/services/ark-api/ark-api.ts
  src/app/services/user-data/user-data.ts
  src/app/utils/ark-utility.ts
  src/app/utils/bignumber.ts
  src/assets/i18n/en.json
  src/assets/styles/auto-complete.pcss
Labels: Complexity: Undetermined, Type: Task

#481 feat: add script to find missing translations
  missing-translations.js
  package.json
  src/assets/i18n/zh.json
Labels: Complexity: High, Type: Feature

#471 refactor: intro screen
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/intro/intro-routing.module.ts
  src/app/intro/intro.component.html
  src/app/intro/intro.component.ts
  src/app/intro/intro.config.ts
  src/app/intro/intro.module.ts
  src/app/intro/intro.pcss
  src/app/intro/intro.spec.ts
  src/app/intro/shared/intro.actions.ts
  src/app/intro/shared/intro.service.ts
  src/app/intro/shared/intro.state.ts
  src/app/intro/shared/intro.type.ts
  src/app/pages/intro/intro.module.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#472 feat: Use NGXs router plugin
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/intro/intro.component.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#484 chore: update pt-br translation
  src/assets/i18n/pt-br.json
Labels: Complexity: Medium, Type: Task

#503 fix: remove unused local notifications provider
  config.xml
  package-lock.json
  package.json
  src/app/services/local-notifications/local-notifications.ts
Labels: Complexity: Medium, Type: Bugfix

#483 refactor: update @angular from 8 to 9
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/modals/custom-network-manage/custom-network-manage.html
  src/app/modals/custom-network-manage/custom-network-manage.module.ts
  src/app/modals/custom-network-manage/custom-network-manage.ts
  src/app/modals/wallet-backup/wallet-backup.html
  src/app/pages/delegates/delegates.ts
  src/app/pages/network-status/network-status.html
  src/app/pages/network-status/network-status.module.ts
  src/app/pages/network-status/network-status.pcss
  src/app/pages/network-status/network-status.ts
  src/app/pages/profiles/profile-create/profile-create.html
  src/app/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.html
  src/app/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.module.ts
  src/app/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.scss
  src/app/pages/wallet/wallet-dashboard/modal/register-delegate/register-delegate.ts
  src/app/pages/wallet/wallet-dashboard/modal/register-second-passphrase/register-second-passphrase.html
  src/app/pages/wallet/wallet-dashboard/modal/register-second-passphrase/register-second-passphrase.module.ts
  src/app/pages/wallet/wallet-dashboard/modal/register-second-passphrase/register-second-passphrase.scss
  src/app/pages/wallet/wallet-dashboard/modal/register-second-passphrase/register-second-passphrase.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.html
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.module.ts
  src/app/pages/wallet/wallet-dashboard/wallet-dashboard.ts
  src/app/pages/wallet/wallet-list/wallet-list.ts
  src/app/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.html
  src/app/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.module.ts
  src/app/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.scss
  src/app/pages/wallet/wallet-top-list/modal/top-wallet-details/top-wallet-details.ts
  src/app/pages/wallet/wallet-top-list/wallet-top-list.html
  src/app/pages/wallet/wallet-top-list/wallet-top-list.module.ts
  src/app/pages/wallet/wallet-top-list/wallet-top-list.scss
  src/app/pages/wallet/wallet-top-list/wallet-top-list.ts
  src/app/services/ark-api/ark-api.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#504 hotfix: Update and propagate wallets property
  src/app/pages/wallet/wallet-list/wallet-list.ts
Labels: Complexity: Low, Type: Bugfix
